# -*- coding: utf-8 -*-
"""Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qedTRV6kh_0_X8CKYzutHv1fukCbnDcJ
"""

from google.colab import drive
drive.mount('/content/drive')

import os

# Point this directly to your unzipped folder in Google Drive
dataset_path = '/content/drive/MyDrive/data_project_Ai'

# Get all the class folders inside the dataset directory
classes = os.listdir(dataset_path)

print("Dataset Class Breakdown:")
print("-" * 30)

total_images = 0
for disease_class in classes:
    class_path = os.path.join(dataset_path, disease_class)

    # Ensure it's a directory and not a hidden system file
    if os.path.isdir(class_path):
        num_images = len(os.listdir(class_path))
        total_images += num_images
        print(f"{disease_class}: {num_images} images")

print("-" * 30)
print(f"Total Images in Dataset: {total_images}")

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import random
import os

def view_random_images(target_dir):
    plt.figure(figsize=(10, 10))

    # Get a list of actual directories (ignoring hidden files)
    valid_classes = [d for d in os.listdir(target_dir) if os.path.isdir(os.path.join(target_dir, d))]

    # Select 9 random classes (or repeat classes if you have fewer than 9)
    random_classes = random.choices(valid_classes, k=9)

    for i, random_class in enumerate(random_classes):
        class_path = os.path.join(target_dir, random_class)

        # Select a random image from that specific class folder
        random_image = random.choice(os.listdir(class_path))
        img_path = os.path.join(class_path, random_image)

        # Read and plot the image
        img = mpimg.imread(img_path)
        plt.subplot(3, 3, i+1)
        plt.imshow(img)
        plt.title(random_class, fontsize=10)
        plt.axis('off')

    plt.tight_layout()
    plt.show()

# Call the function to see your data!
view_random_images(dataset_path)

import os
from PIL import Image

# Use your internal Colab path (not the https:// link)
dataset_path = '/content/drive/MyDrive/data_project_Ai'

unique_sizes = set()

for root, dirs, files in os.walk(dataset_path):
    for file in files:
        if file.lower().endswith(('.png', '.jpg', '.jpeg')):
            img_path = os.path.join(root, file)
            with Image.open(img_path) as img:
                unique_sizes.add(img.size)

print(f"Unique image sizes found: {unique_sizes}")

import os
from PIL import Image

# 1. Define your paths (Use the internal "Copy Path" from the Colab sidebar)
input_path = '/content/drive/MyDrive/data_project_Ai'
output_path = '/content/drive/MyDrive/data_project_Ai_256'

# 2. Create the output directory if it doesn't already exist
if not os.path.exists(output_path):
    os.makedirs(output_path)

print("Starting resize process... this may take a few minutes for 1GB of data.")

# 3. Walk through every subfolder in your original directory [cite: 132, 133]
for root, dirs, files in os.walk(input_path):
    # Replicate the folder structure (e.g., Wheat_Healthy) in the new location
    relative_path = os.path.relpath(root, input_path)
    current_output_dir = os.path.join(output_path, relative_path)

    if not os.path.exists(current_output_dir):
        os.makedirs(current_output_dir)

    for file in files:
        if file.lower().endswith(('.png', '.jpg', '.jpeg')):
            img_path = os.path.join(root, file)
            out_img_path = os.path.join(current_output_dir, file)

            try:
                # 4. Open, resize, and save the image [cite: 24, 126]
                with Image.open(img_path) as img:
                    # Convert to RGB to ensure ResNet50 compatibility [cite: 305, 313]
                    img = img.convert('RGB')

                    # Only resize if it is not already 256x256
                    if img.size != (256, 256):
                        img = img.resize((256, 256), Image.Resampling.LANCZOS)

                    img.save(out_img_path)
            except Exception as e:
                print(f"Error processing {img_path}: {e}")

print(f"Success! All images are now standardized and saved to: {output_path}")

# This will quietly unzip your dataset into a folder named "plant_dataset"
!unzip -q /content/drive/MyDrive/data_project_Ai/archive.zip -d /content/data_project_Ai_256

import os

# Set this to the folder where you extracted your zip file
dataset_path = '/content/plant_dataset/PlantVillage'

# Get all the class folders inside the dataset directory
classes = os.listdir(dataset_path)

print("Dataset Class Breakdown:")
print("-" * 30)

total_images = 0
for disease_class in classes:
    class_path = os.path.join(dataset_path, disease_class)

    # Ensure it's a directory
    if os.path.isdir(class_path):
        num_images = len(os.listdir(class_path))
        total_images += num_images
        print(f"{disease_class}: {num_images} images")

print("-" * 30)
print(f"Total Images in Dataset: {total_images}")

import os
import shutil

# 1. Set your Google Drive paths
# Replace with the path to your folder containing all the loose 256x256 images
source_dir = '/content/drive/MyDrive/data_project_Ai_256/Long 2023 Plant Path 999 photos'

# Replace with the path where you want the new organized folders to be created
target_base_dir = '/content/drive/MyDrive/Organized_Wheat_Dataset_256'

# 2. Define your mapping rules
# This tells the script: "If the filename contains 'YellowRust', put it in 'Wheat_Yellow_Rust'"
disease_mapping = {
    'YellowRust': 'Wheat_Yellow_Rust',
    'BrownRust': 'Wheat_Brown_Rust',   # Add this if you have brown rust
    'Healthy': 'Wheat_Healthy',      # Add this if you have healthy images
    'Septoria':'Septoria',
    'Mildew':'Mildew',
    'BrownRust':'BrownRust'
}

print("Starting to organize the dataset on Google Drive...")

# Create the base target directory if it doesn't exist
if not os.path.exists(target_base_dir):
    os.makedirs(target_base_dir)

moved_count = 0

# 3. Iterate through all the loose files
for filename in os.listdir(source_dir):
    # Only process image files
    if filename.lower().endswith(('.png', '.jpg', '.jpeg')):

        # Check the filename against our mapping dictionary
        for keyword, folder_name in disease_mapping.items():

            # If the keyword (e.g., 'YellowRust') is in the filename
            if keyword.lower() in filename.lower():

                # Create the specific disease target folder if it doesn't exist
                target_folder = os.path.join(target_base_dir, folder_name)
                if not os.path.exists(target_folder):
                    os.makedirs(target_folder)

                # Move the file to the new folder
                src_path = os.path.join(source_dir, filename)
                dest_path = os.path.join(target_folder, filename)

                try:
                    shutil.move(src_path, dest_path)
                    moved_count += 1
                except Exception as e:
                    print(f"Error moving {filename}: {e}")

                # Stop checking other keywords once we found a match
                break

print(f"Success! {moved_count} images have been sorted into proper PlantVillage folders.")

import shutil

# Path to the folder currently in Colab's temporary storage
source = '/content/data_project_Ai_256/PlantVillage'

# Path to where you want it saved PERMANENTLY in your Google Drive
destination = '/content/drive/MyDrive/data_project_ai_256_SAVED'

print("Starting to copy files... this might take a minute.")

try:
    # copytree copies the entire directory and its contents
    shutil.copytree(source, destination)
    print("Success! The folder is now saved to your Google Drive.")
except Exception as e:
    print(f"An error occurred: {e}")

import os
from PIL import Image

# 1. Define your paths
# Replace with the actual path to your PlantVillage dataset
input_path = '/content/data_project_Ai_256/PlantVillage'
# Define the new folder where resized images will be saved
output_path = '/content/drive/MyDrive/PlantVillage_Resized_256'

# 2. Create the output directory if it doesn't already exist
if not os.path.exists(output_path):
    os.makedirs(output_path)

print("Starting resize process... this may take a while depending on the dataset size.")

# 3. Walk through every subfolder in your original directory
for root, dirs, files in os.walk(input_path):
    # Replicate the folder structure (e.g., Tomato_Blight) in the new location
    relative_path = os.path.relpath(root, input_path)
    current_output_dir = os.path.join(output_path, relative_path)

    if not os.path.exists(current_output_dir):
        os.makedirs(current_output_dir)

    for file in files:
        if file.lower().endswith(('.png', '.jpg', '.jpeg')):
            img_path = os.path.join(root, file)
            out_img_path = os.path.join(current_output_dir, file)

            try:
                # 4. Open, resize, and save the image
                with Image.open(img_path) as img:
                    # Convert to RGB to ensure ResNet50 compatibility
                    img = img.convert('RGB')

                    # Only resize if it is not already 256x256
                    if img.size != (256, 256):
                        img = img.resize((256, 256), Image.Resampling.LANCZOS)

                    img.save(out_img_path)
            except Exception as e:
                print(f"Error processing {img_path}: {e}")

print(f"Success! All images are now standardized and saved to: {output_path}")

import tensorflow as tf

base_dir = '/content/drive/MyDrive/PlantVillage_Resized_256'
batch_size = 32
img_size = (224, 224)
seed_val = 42

# Load 80% for Training
train_ds = tf.keras.utils.image_dataset_from_directory(
    base_dir,
    validation_split=0.2,
    subset="training",
    seed=seed_val,
    image_size=img_size,
    batch_size=batch_size,
)

# Load 20% for Validation
val_ds = tf.keras.utils.image_dataset_from_directory(
    base_dir,
    validation_split=0.2,
    subset="validation",
    seed=seed_val,
    image_size=img_size,
    batch_size=batch_size,
)

# Split Validation in half to create Test set (10% Val, 10% Test)
val_batches = tf.data.experimental.cardinality(val_ds)
half_batches = val_batches // 2

test_ds = val_ds.take(half_batches)
val_ds = val_ds.skip(half_batches)

# Extract dataset info
class_names = train_ds.class_names
num_classes = len(class_names)
print(f"\nSuccessfully loaded {num_classes} plant classes.")
print(f"Training Batches: {tf.data.experimental.cardinality(train_ds)}")
print(f"Validation Batches: {tf.data.experimental.cardinality(val_ds)}")
print(f"Testing Batches: {tf.data.experimental.cardinality(test_ds)}")

# Optimize performance
AUTOTUNE = tf.data.AUTOTUNE
train_ds = train_ds.prefetch(buffer_size=AUTOTUNE)
val_ds = val_ds.prefetch(buffer_size=AUTOTUNE)
test_ds = test_ds.prefetch(buffer_size=AUTOTUNE)

import tensorflow as tf
import numpy as np
from sklearn.utils.class_weight import compute_class_weight
from tensorflow.keras.applications import ResNet50
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout, Input, RandomFlip, RandomRotation, RandomZoom
from tensorflow.keras.models import Model

# ==========================================
# 1. BUILD THE MODEL PIPELINE
# ==========================================
data_augmentation = tf.keras.Sequential([
  RandomFlip("horizontal_and_vertical"),
  RandomRotation(0.2),
  RandomZoom(0.2),
])

base_model = ResNet50(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
base_model.trainable = False

inputs = Input(shape=(224, 224, 3))
x = data_augmentation(inputs)
x = tf.keras.applications.resnet50.preprocess_input(x)
x = base_model(x, training=False)
x = GlobalAveragePooling2D()(x)
x = Dropout(0.5)(x)
outputs = Dense(num_classes, activation='softmax')(x)

model = Model(inputs, outputs)
print(f"Keras Model built for {num_classes} classes.")

# ==========================================
# 2. CALCULATE CLASS WEIGHTS (Balancing)
# ==========================================
print("\nCalculating class weights to balance the dataset...")
# Extract all labels from the training dataset
# labels = np.array([y.numpy() for x, y in train_ds.unbatch()])

labels = np.array([y.numpy() for x, y in train_ds.unbatch()])

# Automatically compute heavy penalties for small folders, light penalties for large folders
calculated_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(labels),
    y=labels
)
class_weight_dict = dict(enumerate(calculated_weights))

# ==========================================
# 3. COMPILE AND SET SAFETY NETS
# ==========================================
print("Compiling the model...")
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

checkpoint_path = "/content/drive/MyDrive/best_plant_model.keras"
checkpoint = tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_path, monitor='val_accuracy', save_best_only=True, verbose=1
)

early_stop = tf.keras.callbacks.EarlyStopping(
    monitor='val_loss', patience=5, restore_best_weights=True
)

# ==========================================
# 4. START TRAINING
# ==========================================
EPOCHS = 20

print(f"\nStarting training for {EPOCHS} epochs...")
history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=EPOCHS,
    class_weight=class_weight_dict,     # <--- Your dataset is mathematically balanced here!
    callbacks=[checkpoint, early_stop]
)

print(f"\nTraining Complete! Your best model is safely stored at: {checkpoint_path}")

import tensorflow as tf

model = tf.keras.models.load_model('/content/drive/MyDrive/best_plant_model.keras')

# 2. Test it on the completely unseen testing dataset
print("Testing model on unseen data...")
loss, accuracy = model.evaluate(test_ds)
print(f"Final Test Accuracy: {accuracy * 100:.2f}%")

