# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DUX99c7sYyf_6acv7YlpfdOajeGmfW1A
"""

pip install langchain  langchain-community langchain-text-splitters faiss-cpu python-dotenv

pip install langchain-google-genai

pip install langchain

!pip install -U langchain langchain-community langchain-openai faiss-cpu

!pip

!pip uninstall -y langchain
!pip install langchain

import langchain
print(langchain.__version__)

!pip uninstall -y \
langchain \
langchain-core \
langchain-community \
langchain-google-genai \
langchain-openai \
langchain-classic \
langchain-text-splitters

!pip install \
langchain==0.2.16 \
langchain-core==0.2.43 \
langchain-community==0.2.16 \
langchain-text-splitters==0.2.4 \
langchain-google-genai==1.0.10 \
faiss-cpu

# using namespace std

import os
from dotenv import load_dotenv

# LangChain Imports
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import FAISS
from langchain_core.prompts import ChatPromptTemplate
from langchain.chains.combine_documents import create_stuff_documents_chain
from langchain.chains import create_retrieval_chain

# Gemini Imports
from langchain_google_genai import ChatGoogleGenerativeAI, GoogleGenerativeAIEmbeddings

# ---------------------------------------------------------
# SETUP: API Key Configuration
# ---------------------------------------------------------
load_dotenv()
google_api_key = os.getenv("GOOGLE_API_KEY")

if not google_api_key:
    try:
        from google.colab import userdata
        google_api_key = userdata.get('GOOGLE_API_KEY')
    except ImportError:
        pass

if not google_api_key:
    raise ValueError(
        "GOOGLE_API_KEY not found. Please ensure it's set in your .env file "
        "(e.g., GOOGLE_API_KEY='your_api_key') or as a Colab secret."
    )

os.environ["GOOGLE_API_KEY"] = google_api_key

print("🧠 Booting up the Gemini AI Assistant...")

# ---------------------------------------------------------
# PHASE 1: Reading and Processing the "Textbook"
# ---------------------------------------------------------
print("📚 Reading disease database...")
loader = TextLoader("plant_disease.txt")
documents = loader.load()

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200
)
chunks = text_splitter.split_documents(documents)

# ---------------------------------------------------------
# PHASE 2: Creating the Vector Database (The Index)
# ---------------------------------------------------------
print("🔍 Building the search index...")

# FIX: Using the correct and active Gemini embedding model
embeddings = GoogleGenerativeAIEmbeddings(model="models/gemini-embedding-2")
vector_store = FAISS.from_documents(chunks, embeddings)

retriever = vector_store.as_retriever(search_kwargs={"k": 3})

# ---------------------------------------------------------
# PHASE 3: Setting up the LLM Brain and Prompt
# ---------------------------------------------------------
system_prompt = (
    "You are a helpful agricultural expert. "
    "Use the following retrieved context to answer the user's question about plant diseases and remedies. "
    "If you don't know the answer based on the context, say you don't know. Keep your answers concise.\n\n"
    "CRITICAL INSTRUCTION: You must translate and write your ENTIRE final response in {language}. "
    "If the requested language is Hindi, ensure the script is in Devanagari and completely natural.\n\n"
    "Context: {context}"
)

prompt = ChatPromptTemplate.from_messages([
    ("system", system_prompt),
    ("human", "{input}"),
])

llm = ChatGoogleGenerativeAI(model="gemini-1.5-flash", temperature=0.2)

question_answer_chain = create_stuff_documents_chain(llm, prompt)
rag_chain = create_retrieval_chain(retriever, question_answer_chain)

print("✅ Bot is ready!")
print("-" * 50)

# ---------------------------------------------------------
# PHASE 4: Language Selection & Terminal Chat Loop
# ---------------------------------------------------------
print("\n🌐 Please select your preferred language / कृपया अपनी पसंदीदा भाषा चुनें:")
print("1. English")
print("2. Hindi (हिन्दी)")

lang_choice = input("Enter 1 or 2: ").strip()

if lang_choice == "2":
    selected_language = "Hindi"
    print("\n✅ भाषा हिन्दी सेट कर दी गई है। आप अपने सवाल पूछ सकते हैं। (Type 'exit' to quit)")
else:
    selected_language = "English"
    print("\n✅ Language set to English. You can now ask your questions. (Type 'exit' to quit)")

while True:
    user_input = input("\n🧑‍🌾 You: ")

    if user_input.lower() in ['quit', 'exit', 'q']:
        if selected_language == "Hindi":
            print("अलविदा! खेती के लिए शुभकामनाएँ।")
        else:
            print("Goodbye! Happy farming.")
        break

    response = rag_chain.invoke({
        "input": user_input,
        "language": selected_language
    })

    print(f"\n🤖 Bot: {response['answer']}")

pip install sentence-transformers

!pip install -U langchain==0.2.16
!pip install -U langchain-community==0.2.16
!pip install -U langchain-google-genai==1.0.10
!pip install -U sentence-transformers
!pip install -U faiss-cpu

!pip install -q \
langchain==0.2.16 \
langchain-community==0.2.16 \
langchain-core==0.2.43 \
langchain-google-genai==1.0.10 \
sentence-transformers \
faiss-cpu

import os
from dotenv import load_dotenv

# -----------------------------
# LangChain Imports
# -----------------------------
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import FAISS
from langchain_community.embeddings import HuggingFaceEmbeddings

from langchain_core.prompts import ChatPromptTemplate

from langchain.chains.combine_documents import create_stuff_documents_chain
from langchain.chains import create_retrieval_chain

# -----------------------------
# Gemini Imports
# -----------------------------
from langchain_google_genai import ChatGoogleGenerativeAI

# -----------------------------
# API KEY SETUP
# -----------------------------
load_dotenv()

google_api_key = os.getenv("GOOGLE_API_KEY")

if not google_api_key:
    try:
        from google.colab import userdata
        google_api_key = userdata.get("GOOGLE_API_KEY")
    except:
        pass

if not google_api_key:
    raise ValueError("GOOGLE_API_KEY not found.")

os.environ["GOOGLE_API_KEY"] = google_api_key

print("🧠 Booting Plant Disease AI Assistant...")

# -----------------------------
# Load Disease Database
# -----------------------------
print("📚 Reading disease database...")

loader = TextLoader(
    "plant_disease.txt",
    encoding="utf-8"
)

documents = loader.load()

# -----------------------------
# Create Chunks
# -----------------------------
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=2500,
    chunk_overlap=200
)

chunks = text_splitter.split_documents(documents)

print(f"📄 Generated {len(chunks)} chunks.")

# -----------------------------
# Local Embeddings
# -----------------------------
print("🔍 Loading embedding model...")

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

# -----------------------------
# Create / Load FAISS
# -----------------------------
FAISS_PATH = "faiss_index"

if os.path.exists(FAISS_PATH):

    print("📦 Loading saved FAISS index...")

    vector_store = FAISS.load_local(
        FAISS_PATH,
        embeddings,
        allow_dangerous_deserialization=True
    )

else:

    print("🧠 Creating FAISS index...")

    vector_store = FAISS.from_documents(
        chunks,
        embeddings
    )

    vector_store.save_local(FAISS_PATH)

    print("✅ FAISS index saved.")

# -----------------------------
# Retriever
# -----------------------------
retriever = vector_store.as_retriever(
    search_type="similarity",
    search_kwargs={"k": 4}
)

# -----------------------------
# Prompt
# -----------------------------
system_prompt = """
You are an expert agricultural assistant.

Answer ONLY using the provided context.

If the answer is not available in the context,
say:
'I could not find this information in the disease database.'

Whenever possible provide:

1. Disease Name
2. Symptoms
3. Cause
4. Treatment / Remedy

Write the entire answer in {language}.

Context:
{context}
"""

prompt = ChatPromptTemplate.from_messages(
    [
        ("system", system_prompt),
        ("human", "{input}")
    ]
)

# -----------------------------
# Gemini 2.5 Flash
# -----------------------------
llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    temperature=0.2
)

# -----------------------------
# Build RAG Chain
# -----------------------------
question_answer_chain = create_stuff_documents_chain(
    llm,
    prompt
)

rag_chain = create_retrieval_chain(
    retriever,
    question_answer_chain
)

print("✅ Bot is ready!")
print("-" * 50)

# -----------------------------
# Language Selection
# -----------------------------
print("\n🌐 Select Language")
print("1. English")
print("2. Hindi")

choice = input("Enter 1 or 2: ").strip()

if choice == "2":
    selected_language = "Hindi"
    print("\n✅ हिन्दी भाषा चुनी गई है")
else:
    selected_language = "English"
    print("\n✅ English selected")

# -----------------------------
# Chat Loop
# -----------------------------
while True:

    user_input = input("\n🧑‍🌾 You: ")

    if user_input.lower() in ["exit", "quit", "q"]:

        if selected_language == "Hindi":
            print("अलविदा! खेती के लिए शुभकामनाएँ।")
        else:
            print("Goodbye! Happy Farming.")

        break

    try:

        response = rag_chain.invoke(
            {
                "input": user_input,
                "language": selected_language
            }
        )

        print(f"\n🤖 Bot: {response['answer']}")

    except Exception as e:

        print(f"\n❌ Error: {e}")